### ISSUE TITLE
Tail call optimization (TCO)

### ISSUE THREAD

**Issue by sdingcn** [sdingcn/exprscript#4]
Consider adding TCO to the interpretation process.

**Comment by sdingcn** [comment]
7088ee875173a4e66eefbcd9ff7233d337c4ecbe

**Comment by GoGim1** [comment]
Hi, after reviewing your code, I think we could also add TCO for calling `.call/cc`. What do you think?

This is my test script:
```
letrec (
  outer = lambda (n s) { [
    (.void)
    (.call/cc lambda (k) {
        if (.== n 0) then s
        else 
            letrec (nn = (.- n 1) ss = (.+ s n)) {
                (outer nn ss)
            }
    })
  ]
  }
) {
  (outer 1000 0)
}
```
and outputs :
```
# without TCO 
...
[Note] program value = 500500
User time (seconds) = 11.628
System time (seconds) = 0.088
Peak memory (MiB) = 23.523

# with TCO
...
[Note] program value = 500500
User time (seconds) = 0.863
System time (seconds) = 0.037
Peak memory (MiB) = 11.312
```

**Comment by sdingcn** [comment]
> Hi, after reviewing your code, I think we could also add TCO for calling `.call/cc`. What do you think?
> 
> This is my test script:
> 
> ```
> letrec (
>   outer = lambda (n s) { [
>     (.void)
>     (.call/cc lambda (k) {
>         if (.== n 0) then s
>         else 
>             letrec (nn = (.- n 1) ss = (.+ s n)) {
>                 (outer nn ss)
>             }
>     })
>   ]
>   }
> ) {
>   (outer 1000 0)
> }
> ```
> 
> and outputs :
> 
> ```
> # without TCO 
> ...
> [Note] program value = 500500
> User time (seconds) = 11.628
> System time (seconds) = 0.088
> Peak memory (MiB) = 23.523
> 
> # with TCO
> ...
> [Note] program value = 500500
> User time (seconds) = 0.863
> System time (seconds) = 0.037
> Peak memory (MiB) = 11.312
> ```

Thanks for the comment! In your example, the captured continuation `k` is never used so it's like a normal function call and we can do TCO. I think even if `k` is used, TCO is still possible since in my original implementation, call/cc deep copied the stack (which is inefficient) so removing stack frames won't affect the captured stack.

However, the main branch was changed significantly (with call/cc already removed). :-)
